---
name: module3_task1

"on":  # do something on push to main
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ''

      - name: Installing hugo
      - run: cd module3_task1/ && ./setup.sh

      - name: Validate the makefile
      - run: cd module3_task1/ && make help && make build
