---
name: module3_task3

"on":  # do something on push to main
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ''

      - run: cd module3_task2/ && ./setup.sh

      - run: npm install -g markdownlint-cli

      - run: cd module3_task2/ && make lint

      - run: cd module3_task2/ && make test

      - run: cd module3_task2/ && make package

      - run: cd module3_task2/ && make help && make build

  create-release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v3
      - run: npm install -g markdownlint-cli
      - run: cd module3_task3 && ./setup.sh
      - run: cd module3_task3 && make package

    id: create_release
      - uses: softprops/action-gh-release@v1
    env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    with:
        files: ./module3_task3/awesome-website.zip
        body_path: ./module3_task3/DEPLOY.md

