---
name: module3_task4

on:
  push:
    branches:
      - main
      - master

    tags:
      - '*'

  schedule:
    - cron: '0 0 * * *'

  pull_request:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
        contents: write
        id-token: write

    steps:
      - name: Clone the repositor_1y
        uses: actions/checkout@v3

      - name: installing Hugo_2
        run: cd ./module3_task4 && ./setup.sh

      - name: install the Markdownlint_3
        run: npm install -g markdownlint-cli

      - name: Lint the files_4
        run: cd module3_task4 && make lint

      - name: Tests_5
        run: cd module3_task4 && make test

      - name: Archives the files_6
        run: cd module3_task4 && make package

      - name: validate the Makefile_7
        run: cd module3_task4 && make help && make build

  create-release:
    needs: build
    #if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: install the Markdownlint
        run: npm install -g markdownlint-cli

      - name: Install Hugo
        run: cd ./module3_task4 && ./setup.sh

      - name: Archives the files
        run: cd module3_task4 && make package

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          #release_name: Release ${{ github.ref }}
          #files: ./module3_task3/awesome-website.zip
          #body_path: ./module3_task4/DEPLOY.md
